# Generated by Django 5.2.15 on 2026-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mobile_pass", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="applemobilepassregistration",
            new_name="apple_mobil_device__501a74_idx",
            old_name="django_mobi_device__f0201c_idx",
        ),
        migrations.RenameIndex(
            model_name="applemobilepassregistration",
            new_name="apple_mobil_device__360faf_idx",
            old_name="django_mobi_device__7df3b0_idx",
        ),
        migrations.RenameIndex(
            model_name="googlemobilepassevent",
            new_name="mobile_pass_mobile__7f1ac2_idx",
            old_name="django_mobi_mobile__8f9460_idx",
        ),
        migrations.RenameIndex(
            model_name="googlemobilepassevent",
            new_name="mobile_pass_receive_670a4a_idx",
            old_name="django_mobi_receive_0315fd_idx",
        ),
        migrations.AlterField(
            model_name="mobilepass",
            name="platform",
            field=models.CharField(
                choices=[("apple", "apple"), ("google", "google")], max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="mobilepass",
            name="type",
            field=models.CharField(
                choices=[
                    ("boardingPass", "boardingPass"),
                    ("coupon", "coupon"),
                    ("eventTicket", "eventTicket"),
                    ("storeCard", "storeCard"),
                    ("generic", "generic"),
                ],
                max_length=32,
            ),
        ),
    ]
